### ISSUE TITLE
Different results between odeint-python and lsoda-C to solve ODEs

### ISSUE THREAD

**Issue by wusmmm** [APMonitor/pdc#1]
Hello Dr. John, 
    Recently, I learned how to use the odeint to solve ODEs with your video in youtube, and I have attamped to use  odeint in python and lsoda in C to solve ODEs, however, I got the some different results from two version.
    Could you help me to check the code and  give some judgement about the resluts, whether is it reasonable? 
    
     The result from C lsoda is attached in the end !

Shi Wu

The lsoda code in C language can be found in github :  _https://github.com/sdwfrost/liblsoda_
Here is my python code for solving ODEs ：
`#!/usr/bin/python
# -*- coding: UTF-8 -*-
'''
  *** The code is author by Wustone ***
  ***              2022-03-04       ***
This code is an example of scipy.odeint to solve ODEs.
odeint is a python version of lsoda

'''
import numpy as np
from scipy.integrate import odeint
import matplotlib.pyplot as plt

neq = 3
ydot = np.zeros(neq)

#function that returns dz/dt
def model(y,t):
    ydot[0] = 1e4*y[1]*y[2] - 0.04*y[0]
    ydot[2] = 3e7*y[1]*y[1]
    ydot[1] = -(ydot[0] + ydot[2])    
    return ydot

# initial value
y0 = [1.0e0, 0.0, 0.0]

# time points
t = [0.0, 0.4, 4, 40, 400, 4e3, 4e4, 4e5, 4e6, 4e7, 4e8, 4e9, 4e10]

# solve ODE
y = odeint(model, y0, t, atol = 1e-15, rtol = 1e-10)

# print results
for i in range(0, len(t)):
    print('at t= ','{:2e}'.format(t[i]), '   y=','{:2e}   {:2e}   {:2e}'.format(y[i,0],y[i,1],y[i,2]))
    
# plot results
plt.figure(num=1, figsize = (8,6))
plt.loglog(t,y[:,0], 'b-', label=r'y[0]')
plt.loglog(t,y[:,1], 'r--', label=r'y[1]')
plt.loglog(t,y[:,2], 'g:', label=r'y[2]')
plt.xlabel('time')
plt.ylabel('reponse')
plt.legend(loc='best')
plt.show()

'''
 result from Fortran version of lsoda
 
 The correct answer (up to certain precision):

 at t=   4.0000e-01 y=   9.851712e-01   3.386380e-05   1.479493e-02
 at t=   4.0000e+00 y=   9.055333e-01   2.240655e-05   9.444430e-02
 at t=   4.0000e+01 y=   7.158403e-01   9.186334e-06   2.841505e-01
 at t=   4.0000e+02 y=   4.505250e-01   3.222964e-06   5.494717e-01
 at t=   4.0000e+03 y=   1.831976e-01   8.941773e-07   8.168015e-01
 at t=   4.0000e+04 y=   3.898729e-02   1.621940e-07   9.610125e-01
 at t=   4.0000e+05 y=   4.936362e-03   1.984221e-08   9.950636e-01
 at t=   4.0000e+06 y=   5.161833e-04   2.065787e-09   9.994838e-01
 at t=   4.0000e+07 y=   5.179804e-05   2.072027e-10   9.999482e-01
 at t=   4.0000e+08 y=   5.283675e-06   2.113481e-11   9.999947e-01
 at t=   4.0000e+09 y=   4.658667e-07   1.863468e-12   9.999995e-01
 at t=   4.0000e+10 y=   1.431100e-08   5.724404e-14   1.000000e+00
'''
`

**Comment by APMonitor** [comment]
I can't help with the details of the many specific requests that I receive each week. I recommend that you find another ODE solver such as MATLAB ode15s or ode23 to compare the solutions. A higher-order Runga Kutta method may help. The third equation looks like it is susceptible to numerical drift. Increasing the number of time steps can also help.
